packages:
  - apps/*
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: false
  prisma: true
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.21.0'
  - '@eslint-react/core@5.21.0'
  - '@eslint-react/eslint-plugin@5.21.0'
  - '@eslint-react/eslint@5.21.0'
  - '@eslint-react/jsx@5.21.0'
  - '@eslint-react/shared@5.21.0'
  - '@eslint-react/var@5.21.0'
  - eslint-plugin-react-dom@5.21.0
  - eslint-plugin-react-jsx@5.21.0
  - eslint-plugin-react-naming-convention@5.21.0
  - eslint-plugin-react-rsc@5.21.0
  - eslint-plugin-react-web-api@5.21.0
  - eslint-plugin-react-x@5.21.0
