import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const rootEnvPath = path.join(rootDir, ".env");
const rootExamplePath = path.join(rootDir, ".env.example");
const backendEnvPath = path.join(rootDir, "apps", "backend", ".env");
const frontendEnvPath = path.join(rootDir, "apps", "frontend", ".env.local");

function parseEnv(contents) {
  const env = {};

  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const separatorIndex = line.indexOf("=");
    if (separatorIndex === -1) continue;

    const key = line.slice(0, separatorIndex).trim();
    let value = line.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

function readRootEnv() {
  if (fs.existsSync(rootEnvPath)) {
    return {
      sourcePath: rootEnvPath,
      values: parseEnv(fs.readFileSync(rootEnvPath, "utf8")),
    };
  }

  if (fs.existsSync(rootExamplePath)) {
    return {
      sourcePath: rootExamplePath,
      values: parseEnv(fs.readFileSync(rootExamplePath, "utf8")),
    };
  }

  throw new Error("Missing `.env` and `.env.example` at the repo root.");
}

function writeEnvFile(targetPath, lines) {
  fs.writeFileSync(targetPath, `${lines.join("\n")}\n`, "utf8");
}

const { sourcePath, values } = readRootEnv();

const backendPort = values.BACKEND_PORT || "5001";
const frontendPort = values.FRONTEND_PORT || "8000";

const backendLines = [
  "# Generated by `pnpm env:sync` from the root shared env file.",
  `PORT=${backendPort}`,
  `DATABASE_URL=${values.DATABASE_URL || `mysql://root:${values.MYSQL_ROOT_PASSWORD || "admin"}@localhost:${values.MYSQL_PORT || "3306"}/${values.MYSQL_DATABASE || "gitbee"}`}`,
  `WEB_URL=${values.WEB_URL || `http://localhost:${frontendPort}`}`,
  `JWT_SECRET=${values.JWT_SECRET || "change-me"}`,
  `COOKIE_NAME=${values.COOKIE_NAME || "gitbee_token"}`,
  `BLUEJACK_API=${values.BLUEJACK_API || ""}`,
  `ATLANTIS_API=${values.ATLANTIS_API || ""}`,
];

const frontendLines = [
  "# Generated by `pnpm env:sync` from the root shared env file.",
  `NEXT_PUBLIC_BACKEND_API=${values.NEXT_PUBLIC_BACKEND_API || `http://localhost:${backendPort}/api/`}`,
  `NEXT_PUBLIC_CLIENT_ID=${values.NEXT_PUBLIC_CLIENT_ID || ""}`,
  `NEXT_PUBLIC_TENANT_ID=${values.NEXT_PUBLIC_TENANT_ID || ""}`,
  `NEXT_PUBLIC_REDIRECT_URI=${values.NEXT_PUBLIC_REDIRECT_URI || `http://localhost:${frontendPort}/login`}`,
  `NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI=${values.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI || `http://localhost:${frontendPort}/login`}`,
  `NEXT_PUBLIC_STORE_AUTH_STATE_IN_COOKIE=${values.NEXT_PUBLIC_STORE_AUTH_STATE_IN_COOKIE || "false"}`,
  `NEXT_PUBLIC_CACHE_LOCATION=${values.NEXT_PUBLIC_CACHE_LOCATION || "sessionStorage"}`,
];

writeEnvFile(backendEnvPath, backendLines);
writeEnvFile(frontendEnvPath, frontendLines);

console.log(`Shared env source: ${path.relative(rootDir, sourcePath)}`);
console.log(`Generated ${path.relative(rootDir, backendEnvPath)}`);
console.log(`Generated ${path.relative(rootDir, frontendEnvPath)}`);
